### ISSUE TITLE
ComWrappers crashing with Windows.Forms.Clipboard.SetText and SetDataObject

### ISSUE THREAD

**Issue by lee-io** [kant2002/WinFormsComInterop#54] opened 2023-01-07 15:20 UTC
System.NotImplementedException: The method or operation is not implemented.
   at WinFormsComInterop.WinFormsComWrappers.ComputeVtables(Object, CreateComInterfaceFlags, Int32&) + 0x160
   at System.Runtime.InteropServices.ComWrappers.CreateCCW(Object, CreateComInterfaceFlags) + 0x36
   at System.Runtime.InteropServices.ComWrappers.<>c__DisplayClass25_0.<GetOrCreateComInterfaceForObject>b__0(Object) + 0x1c

**Comment by kant2002** [comment] 2023-01-08 08:35
this is essentially duplicate of #51 and probably you give that you use clipboard quite possible that you need #50 too. I working on that.

**Closed by kant2002** 2023-01-08 08:35 UTC

**Comment by lee-io** [comment] 2023-01-08 20:45
OK, thanks!
